<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kategori_produk_model extends CI_Model
{

    public $table = 'kategori_produk';
    public $id = 'id';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get data by id
    function get_id($k)
    {
        $this->db->where("kategori", $k);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
    $this->db->or_like('kategori', $q);
    $this->db->from($this->table);
        return $this->db->count_all_results();
    }
    
    // get total rows
    function total_rows_produk($q = NULL) {
        return $this->db->query("SELECT COUNT(id) AS c FROM kategori_produk")->row()->c;
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
    $this->db->or_like('kategori', $q);
    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    // get data with limit and search
    function get_limit_data_produk($limit, $start = 0, $q = NULL) {
        $sq = $q!=NULL?" WHERE kategori_produk.kategori LIKE '%$q%'":NULL;

        return $this->db->query("SELECT kategori_produk.*, COUNT(produk.id) AS c FROM `kategori_produk` LEFT OUTER JOIN produk ON kategori_produk.kategori=produk.kategori$sq GROUP BY kategori_produk.kategori")->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kategori_produk_model.php */
/* Location: ./application/models/Kategori_produk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-01-30 05:42:47 */
/* http://harviacode.com */