<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Produk_model extends CI_Model
{

    public $table = 'produk';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function generate_id()
    {
        return ($this->db->query("SELECT MAX(id) AS c FROM produk")->row()->c + 1);
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_gambar($id)
    {
        $this->db->where("id_produk", $id);
        return $this->db->get("gambar_produk")->result();
    }

    // get data by id
    function get_produk_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table."_view")->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
        $this->db->or_like('judul', $q);
        $this->db->or_like('kategori', $q);
        $this->db->or_like('harga', $q);
        $this->db->or_like('deskripsi', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }
    
    // get total rows
    function total_rows_produk($q = NULL) {
        if($q!=NULL){
            $this->db->like('kategori', $q);
            $this->db->or_like('judul', $q);
            $this->db->or_like('deskripsi', $q);
        };
        $this->db->group_by("id");
        $this->db->from($this->table."_view");
        return $this->db->count_all_results();
    }
    
    // get total rows
    function total_rows_produk_kategori($idk, $q = NULL) {
        $sq = $q!=NULL?" AND (produk.judul LIKE '%$q%' OR produk.kategori LIKE '%$q%' OR produk.deskripsi LIKE '%$q%)":NULL;
        $t = $this->db->query("SELECT count(produk.id) AS c FROM produk INNER JOIN kategori_produk ON produk.kategori=kategori_produk.kategori WHERE (kategori_produk.id = $idk)$sq GROUP BY produk.id")->row();
        return (isset($t->c)?$t->c:0);
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('judul', $q);
        $this->db->or_like('kategori', $q);
        $this->db->or_like('harga', $q);
        $this->db->or_like('deskripsi', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // get data with limit and search
    function get_limit_data_produk($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        if($q!=NULL){
            $this->db->like('kategori', $q);
            $this->db->or_like('judul', $q);
            $this->db->or_like('deskripsi', $q);
        };
        $this->db->group_by("id");
        $this->db->limit($limit, $start);
        return $this->db->get($this->table."_view")->result();
    }

    // get data with limit and search
    function get_limit_data_produk_kategori($idk, $limit, $start = 0, $q = NULL) {
        $sq = $q!=NULL?" AND (produk_view.judul LIKE '%$q%' OR produk_view.kategori LIKE '%$q%' OR produk_view.deskripsi LIKE '%$q%)":NULL;
        return $this->db->query("SELECT produk_view.* FROM produk_view INNER JOIN kategori_produk ON produk_view.kategori=kategori_produk.kategori WHERE (kategori_produk.id = $idk)$sq GROUP BY produk_view.id")->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    function insert_gambar($data)
    {
        $this->db->insert("gambar_produk", $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);

        $this->delete_gambar($id);
    }

    // delete data
    function delete_gambar($id)
    {
        $g = $this->db->where("id_produk", $id)->get("gambar_produk")->result();
        foreach ($g as $key => $value) {
            unlink($value->gambar);
        }
        $this->db->where("id_produk", $id);
        $this->db->delete("gambar_produk");
    }

}

/* End of file Produk_model.php */
/* Location: ./application/models/Produk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-01-30 05:42:47 */
/* http://harviacode.com */