<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Perusahaan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        if($this->session->userdata("id") == NULL){
            redirect("Home");
        };
        $this->load->model('Perusahaan_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $data = array(
            'judul_teks_depan' => $this->Perusahaan_model->get_by_id("judul_teks_depan"),
            'isi_teks_depan' => $this->Perusahaan_model->get_by_id("isi_teks_depan"),
            'alamat_perusahaan' => $this->Perusahaan_model->get_by_id("alamat_perusahaan"),
            'tentang' => $this->Perusahaan_model->get_by_id("tentang"),
            'telepon' => $this->Perusahaan_model->get_by_id("telepon"),
            'whatsapp1' => $this->Perusahaan_model->get_by_id("whatsapp1"),
            'whatsapp2' => $this->Perusahaan_model->get_by_id("whatsapp2"),
            'facebook' => $this->Perusahaan_model->get_by_id("facebook"),
            'twitter' => $this->Perusahaan_model->get_by_id("twitter"),
            'instagram' => $this->Perusahaan_model->get_by_id("instagram"),
            'konten'=>'admin/perusahaan/perusahaan_list',
        );
        $this->load->view('admin/container', $data);
    }
    
    public function update_action() 
    {
        $data = array(
            'nilai' => $this->input->post('judul_teks_depan',TRUE),
        );
        $this->Perusahaan_model->update("judul_teks_depan", $data);
        
        $data = array(
            'nilai' => $this->input->post('isi_teks_depan',TRUE),
        );
        $this->Perusahaan_model->update("isi_teks_depan", $data);
        
        $data = array(
            'nilai' => $this->input->post('alamat_perusahaan',TRUE),
        );
        $this->Perusahaan_model->update("alamat_perusahaan", $data);
        
        $data = array(
            'nilai' => $this->input->post('tentang',TRUE),
        );
        $this->Perusahaan_model->update("tentang", $data);
        
        $data = array(
            'nilai' => $this->input->post('telepon',TRUE),
        );
        $this->Perusahaan_model->update("telepon", $data);
        
        $data = array(
            'nilai' => $this->input->post('whatsapp1',TRUE),
        );
        $this->Perusahaan_model->update("whatsapp1", $data);
        
        $data = array(
            'nilai' => $this->input->post('whatsapp2',TRUE),
        );
        $this->Perusahaan_model->update("whatsapp2", $data);
        
        $data = array(
            'nilai' => $this->input->post('facebook',TRUE),
        );
        $this->Perusahaan_model->update("facebook", $data);
        
        $data = array(
            'nilai' => $this->input->post('twitter',TRUE),
        );
        $this->Perusahaan_model->update("twitter", $data);
        
        $data = array(
            'nilai' => $this->input->post('instagram',TRUE),
        );
        $this->Perusahaan_model->update("instagram", $data);


        $this->session->set_flashdata('message', 'Profil Perusahaan Berhasil diperbarui');
        redirect(site_url('admin/Perusahaan'));
    }

}

/* End of file Perusahaan.php */
/* Location: ./application/controllers/Perusahaan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-01-30 05:42:47 */
/* http://harviacode.com */